name: Swift Space Battle
full_name: Swift Space Battle
author: Luan Orlandi
version_code: 100
version_name: 1.1.0
sdk:
  repository: https://github.com/moai/moai-dev.git
  ref: "1.5-stable"

modules:
  BOX2D: true
  CHIPMUNK: true
  CURL: true
  CRYPTO: true
  EXPAT: true
  FREETYPE: true
  HTTP_CLIENT: true
  JSON: true
  JPG: true
  LUAEXT: true
  MONGOOSE: true
  OGG: true
  OPENSSL: true
  SQLITE3: true
  TINYXML: true
  PNG: true
  SFMT: true
  VORBIS: true
  UNTZ: true
  LUAJIT: true

extensions:
     miscellaneous: no
     adcolony: no
     billing: no
     chartboost: no
     crittercism: no
     facebook: no
     push: no
     tapjoy: no
     twitter: no
     tstorewall: no
     tstoregamecenter: no